### ISSUE TITLE
Set 'tester' for other nodes in topology

### ISSUE THREAD

**Issue by bregman-arie** [rhos-infra/InfraRed#177]
What I'm trying to do: I'm running openstack provisioner to provision one single controller node and then I'm running ir-tester to run tests on it

What is wrong: controller is not part of [tester] group, only undercloud is, so all tasks are skipped.

What I want: a simple way to tag with ir-provisioner the controller as my chosen tester node.

**Comment by yfried-redhat** [comment]
@bregman-arie Is this still an issue?

**Comment by bregman-arie** [comment]
Yes
