### ISSUE TITLE
rhbz1302047 workaround starts nova-compute on the controller nodes

### ISSUE THREAD

**Issue by mcornea** [rhos-infra/InfraRed#181]
The workaround for rhbz1302047 starts the nova-compute service on the controller nodes. The nova-compute service should only be started on the compute nodes:

[stack@undercloud ~]$ nova service-list
+----+------------------+------------------------------------+----------+---------+-------+----------------------------+-----------------+
| Id | Binary           | Host                               | Zone     | Status  | State | Updated_at                 | Disabled Reason |
+----+------------------+------------------------------------+----------+---------+-------+----------------------------+-----------------+
| 2  | nova-scheduler   | overcloud-controller-0.localdomain | internal | enabled | up    | 2016-04-19T19:15:56.000000 | -               |
| 5  | nova-scheduler   | overcloud-controller-1.localdomain | internal | enabled | up    | 2016-04-19T19:15:57.000000 | -               |
| 8  | nova-scheduler   | overcloud-controller-2.localdomain | internal | enabled | up    | 2016-04-19T19:15:56.000000 | -               |
| 11 | nova-consoleauth | overcloud-controller-2.localdomain | internal | enabled | up    | 2016-04-19T19:15:54.000000 | -               |
| 14 | nova-consoleauth | overcloud-controller-1.localdomain | internal | enabled | up    | 2016-04-19T19:16:00.000000 | -               |
| 17 | nova-consoleauth | overcloud-controller-0.localdomain | internal | enabled | up    | 2016-04-19T19:15:53.000000 | -               |
| 20 | nova-conductor   | overcloud-controller-2.localdomain | internal | enabled | up    | 2016-04-19T19:15:56.000000 | -               |
| 26 | nova-conductor   | overcloud-controller-0.localdomain | internal | enabled | up    | 2016-04-19T19:15:56.000000 | -               |
| 32 | nova-compute     | overcloud-compute-0.localdomain    | nova     | enabled | up    | 2016-04-19T19:15:54.000000 | -               |
| 35 | nova-conductor   | overcloud-controller-1.localdomain | internal | enabled | up    | 2016-04-19T19:15:55.000000 | -               |
| 38 | nova-compute     | overcloud-controller-0.localdomain | nova     | enabled | up    | 2016-04-19T19:15:56.000000 | -               |
| 41 | nova-compute     | overcloud-controller-1.localdomain | nova     | enabled | up    | 2016-04-19T19:16:00.000000 | -               |
| 44 | nova-compute     | overcloud-controller-2.localdomain | nova     | enabled | up    | 2016-04-19T19:15:57.000000 | -               |
+----+------------------+------------------------------------+----------+---------+-------+----------------------------+-----------------+

[stack@undercloud ~]$ nova hypervisor-list
+----+------------------------------------+-------+---------+
| ID | Hypervisor hostname                | State | Status  |
+----+------------------------------------+-------+---------+
| 2  | overcloud-compute-0.localdomain    | up    | enabled |
| 5  | overcloud-controller-0.localdomain | up    | enabled |
| 8  | overcloud-controller-1.localdomain | up    | enabled |
| 11 | overcloud-controller-2.localdomain | up    | enabled |
+----+------------------------------------+-------+---------+

**Comment by tkammer** [comment]
Thanks Marius!
Looking into this now

**Comment by yfried-redhat** [comment]
@tkammer Please update the status of this issue
