### ISSUE TITLE
[debugging][urgent] Add preview for ansible.ssh.config file in job log

### ISSUE THREAD

**Issue by fhubik** [rhos-infra/InfraRed#214]
A user who wants to debug IR OSPd jenkins job issues wants to know how to (forward) SSH to OC nodes, this file is stored on slave, though. We need to come up with some solution with this soon, several people asked about this.

First suggestion: print ansible.ssh.config to screen (log) during deployment or archive this file as an artifact.

Any other ideas?

**Comment by mcornea** [comment]
We could also add the undercloud in the virthost's /etc/hosts and use the undercloud as a jump host to the overcloud nodes. When you need to debug you ssh to the virthost, then do 'ssh undercloud' and from there do the usual debugging steps.
