### ISSUE TITLE
Enable ansible-lint ANSIBLE0006 for InfraRed

### ISSUE THREAD

**Issue by mpryc** [rhos-infra/InfraRed#250]

**Comment by tkammer** [comment]
@mpryc Hey, this project is being managed by gerrithub[1] and downstream JIRA (until the project moves upstream), could you please open such issues in our JIRA? also, you can find us on IRC at #infrared (freenode) or #rhos-infrared in redhat.

[1] - https://review.gerrithub.io/#/q/project:rhosqeauto/InfraRed+status:open
