### ISSUE TITLE
enable Travis CI on infrared

### ISSUE THREAD

**Issue by ssbarnea** [rhos-infra/InfraRed#278]
Please enable Travis CI on infrared repository, this is an essential tool for providing feedback regarding infrared stability and also helps validating PRs.

I already did the work needed for enabling Travis in my working fork and you can see the results at https://travis-ci.org/ssbarnea/InfraRed/branches 

Current Travis configuration is to perform 3 builds: 
* py27-linux(all tests)
* py35-linux
* py27-osx

This should catch most errors without the risk of creating too many builds. 

Please note that I am willing to take care of Travis integration if further help is needed. 

I know that we already have internal gates for testing it but using Travis in parallel is much more open approach because anyone forking infrared can use travis to test his changes, something that is not possible with gerrit approach.

I will open both a PR on github and a Gerrit review with these changes.

**Comment by tkammer** [comment]
@ssbarnea  Hey, this project is being managed by gerrithub[1] and downstream JIRA (until the project moves upstream), could you please open such issues in our JIRA? also, you can find us on IRC at #infrared (freenode) or #rhos-infrared in redhat.

[1] - https://review.gerrithub.io/#/q/project:rhosqeauto/InfraRed+status:open

**Comment by ssbarnea** [comment]
I copied it to https://projects.engineering.redhat.com/browse/RHOSINFRA-571 and assigned to me.
