### ISSUE TITLE
upgrade ansible-lint to current version

### ISSUE THREAD

**Issue by ssbarnea** [rhos-infra/InfraRed#280]
The current version of  ansible-lint used by infrared is very old and incompatible with py2 and ansible 2.2, we need to upgrade it.

I already succeeded using the latest version `ansible-lint>=3.4.8` and I will submit a PR. 

Please note that newer versions of ansible-lint introduced lots of new tests, which means that we either have to disable them temporary in order to avoid breaking the gates or to fix them.

Current exceptions: `ANSIBLE0006,ANSIBLE0007`

New ones needed: ` ANSIBLE0010,ANSIBLE0011,ANSIBLE0012,ANSIBLE0013,ANSIBLE0014,ANSIBLE0015,ANSIBLE0016 FILE`

I can try to address some of them but I am afraid that this could make the change set too broad. I would recommend on fixing each of them in a different fix, after we first upgrade the linter.

**Comment by tkammer** [comment]
@ssbarnea  Hey, this project is being managed by gerrithub[1] and downstream JIRA (until the project moves upstream), could you please open such issues in our JIRA? also, you can find us on IRC at #infrared (freenode) or #rhos-infrared in redhat.

[1] - https://review.gerrithub.io/#/q/project:rhosqeauto/InfraRed+status:open

**Comment by ssbarnea** [comment]
@tkammer something is wrong with gerrit, the link above displays an empty page but I know for sure that I already have an open review on InfraRed, here is the link to it https://review.gerrithub.io/c/306987/

**Comment by yfried-redhat** [comment]
@ssbarnea the review in your link has been merged, which is why it's not listed under @tkammer's link.
Please see here: https://review.gerrithub.io/#/q/project:rhosqeauto/InfraRed+owner:ssbarnea
