### ISSUE TITLE
Print caller information to the log

### ISSUE THREAD

**Issue by obaranov** [rhos-infra/InfraRed#59]
From current log it's very hard to get any useful information from what module/method/class the log line was printed. I'd suggest to add that information to simplify debug process.

We can do next: 
1) Add %(module)s and %(funcName)s to the logger message format. But this will now work good for classes and objects.
2) Do not use one name for all the logger. Each class/module need to create own logger with: 

```
LOG = logging.getLogger(self.__class__.__name__) 
```

And after that add logger name (%(name)s) to the logger message format. 

My vote is for option 2).

**Comment by tkammer** [comment]
+1 on 2)  ;)
It's much more readable the second option

**Comment by yfried-redhat** [comment]
:+1:

**Comment by aopincar** [comment]
Agree.
Also think we shouldn't use the third party module 'colorlog'.

**Comment by yfried-redhat** [comment]
@obaranov Is this still an issue?

**Comment by obaranov** [comment]
@yfried-redhat yup, we still do not see who printed DEBUG message to the log.
